### PR TITLE
Add CI

### PR DESCRIPTION
**Pull request by hax0kartik**
This PR adds CI via Github Actions. 
Currently, builds will be uploaded as artifacts and will be available in the "actions" tab, I decided against uploading the builds to Releases as it will clog up the releases.

Fixes issue #17 

Example run(binaries available under "Artifacts"):-https://github.com/hax0kartik/Corgi3DS/actions/runs/138167872

**Note the binaries aren't static, so users will need to provide the required dlls/ install the necessary packages.**

### CODE REVIEW

**Comment by flTobi** [comment]
uhhm isn't `ENABLE_COMPATIBILITY_REPORTING` a flag from yuzu?

**Comment by hax0kartik** [comment]
> uhhm isn't `ENABLE_COMPATIBILITY_REPORTING` a flag from yuzu?

No, its something from another 3ds project I worked on and forgot to remove, thanks for pointing out! \:)

**Review by PSI-Rockin — CHANGES_REQUESTED** [review]
I'd like for you to cleanup the YML file by removing the default comments that come with a new Actions project before merging this.

**Comment by hax0kartik** [comment]
@PSI-Rockin Done.

**Pull request merged**
